apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-application4
spec:
  selector:
    app: application4
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: LoadBalancer  # This makes the service accessible through a Load Balancer

